[text]
dpi=30
size=150
hinting="none"
scaling_factor=2
font_path="sans.ttf"

[resolution]
enabled=true
x=210
y=210

[output]
letters_per_frame=1
shake_font=false
anti_aliasing=false
gif=false
path="out"